version: '3.2'
services:
  mongodb:
    container_name: mongo-example
    environment:
      - MONGO_INITDB_DATABASE=example
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=ASjkjasd13123
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - './data:/data/db'
      - './init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js'
  backend:
    container_name: api-example
    build: ./
    ports:
      - '8080:80'
    environment: 
      - DATABASE_URL=mongodb://admin:ASjkjasd13123@mongodb:27017/?authSource=example
    depends_on:
      - mongodb
    restart: always